repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^(LICENSE-3rdparty\.csv|NOTICE)
      - id: trailing-whitespace
        exclude: ^(LICENSE-3rdparty\.csv|NOTICE)
  - repo: local
    hooks:
      - id: terraform-format
        name: format terraform
        entry: terraform fmt -recursive .
        language: system
        types: [terraform]
      - id: terraform-docs
        name: generate terraform docs
        entry: bash -c "find modules -type d -maxdepth 1 -mindepth 1 | xargs -I{} terraform-docs {} --config .terraform-docs.yml"
        language: system
        types: [terraform]
