# DO NOT EDIT: This file is generated by terraform-autogen. Update the autogen_config.json file to change the generated code.

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 4.37.0"
    }
  }
}
