# Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
# This product includes software developed at Datadog (https://www.datadoghq.com/) Copyright 2025 Datadog, Inc.

# DO NOT EDIT: This file is generated by terraform-autogen. Update the autogen_config.json file to change the generated code.

output "app_settings" {
  description = <<DESCRIPTION
A map of key-value pairs of App Settings.
DESCRIPTION
  value       = azurerm_windows_web_app.this.app_settings
  sensitive   = true
}

output "client_affinity_enabled" {
  description = <<DESCRIPTION
Should Client Affinity be enabled?
DESCRIPTION
  value       = azurerm_windows_web_app.this.client_affinity_enabled
}

output "client_certificate_enabled" {
  description = <<DESCRIPTION
Should Client Certificates be enabled?
DESCRIPTION
  value       = azurerm_windows_web_app.this.client_certificate_enabled
}

output "client_certificate_exclusion_paths" {
  description = <<DESCRIPTION
Paths to exclude when using client certificates, separated by ;
DESCRIPTION
  value       = azurerm_windows_web_app.this.client_certificate_exclusion_paths
}

output "client_certificate_mode" {
  description = <<DESCRIPTION
The Client Certificate mode. Possible values are `Required`, `Optional`, and `OptionalInteractiveUser`. This property has no effect when `client_certificate_enabled` is `false`. Defaults to `Required`.
DESCRIPTION
  value       = azurerm_windows_web_app.this.client_certificate_mode
}

output "custom_domain_verification_id" {
  description = <<DESCRIPTION
The identifier used by App Service to perform domain ownership verification via DNS TXT record.
DESCRIPTION
  value       = azurerm_windows_web_app.this.custom_domain_verification_id
  sensitive   = true
}

output "default_hostname" {
  description = <<DESCRIPTION
The default hostname of the Windows Web App.
DESCRIPTION
  value       = azurerm_windows_web_app.this.default_hostname
}

output "enabled" {
  description = <<DESCRIPTION
Should the Windows Web App be enabled? Defaults to `true`.
DESCRIPTION
  value       = azurerm_windows_web_app.this.enabled
}

output "ftp_publish_basic_authentication_enabled" {
  description = <<DESCRIPTION
Should the default FTP Basic Authentication publishing profile be enabled. Defaults to `true`.
DESCRIPTION
  value       = azurerm_windows_web_app.this.ftp_publish_basic_authentication_enabled
}

output "hosting_environment_id" {
  description = <<DESCRIPTION
The ID of the App Service Environment used by App Service.
DESCRIPTION
  value       = azurerm_windows_web_app.this.hosting_environment_id
}

output "https_only" {
  description = <<DESCRIPTION
Should the Windows Web App require HTTPS connections. Defaults to `false`.
DESCRIPTION
  value       = azurerm_windows_web_app.this.https_only
}

output "id" {
  description = <<DESCRIPTION
The ID of the Windows Web App.
DESCRIPTION
  value       = azurerm_windows_web_app.this.id
}

output "key_vault_reference_identity_id" {
  description = <<DESCRIPTION
The User Assigned Identity ID used for accessing KeyVault secrets. The identity must be assigned to the application in the `identity` block. [For more information see - Access vaults with a user-assigned identity](https://docs.microsoft.com/azure/app-service/app-service-key-vault-references#access-vaults-with-a-user-assigned-identity)
DESCRIPTION
  value       = azurerm_windows_web_app.this.key_vault_reference_identity_id
}

output "kind" {
  description = <<DESCRIPTION
The Kind value for this Windows Web App.
DESCRIPTION
  value       = azurerm_windows_web_app.this.kind
}

output "location" {
  description = <<DESCRIPTION
The Azure Region where the Windows Web App should exist. Changing this forces a new Windows Web App to be created.
DESCRIPTION
  value       = azurerm_windows_web_app.this.location
}

output "name" {
  description = <<DESCRIPTION
The name which should be used for this Windows Web App. Changing this forces a new Windows Web App to be created.
DESCRIPTION
  value       = azurerm_windows_web_app.this.name
}

output "outbound_ip_address_list" {
  description = <<DESCRIPTION
A list of outbound IP addresses - such as `["52.23.25.3", "52.143.43.12"]`
DESCRIPTION
  value       = azurerm_windows_web_app.this.outbound_ip_address_list
}

output "outbound_ip_addresses" {
  description = <<DESCRIPTION
A comma separated list of outbound IP addresses - such as `52.23.25.3,52.143.43.12`.
DESCRIPTION
  value       = azurerm_windows_web_app.this.outbound_ip_addresses
}

output "possible_outbound_ip_address_list" {
  description = <<DESCRIPTION
A list of possible outbound ip address.
DESCRIPTION
  value       = azurerm_windows_web_app.this.possible_outbound_ip_address_list
}

output "possible_outbound_ip_addresses" {
  description = <<DESCRIPTION
A comma separated list of outbound IP addresses - such as `52.23.25.3,52.143.43.12,52.143.43.17` - not all of which are necessarily in use. Superset of `outbound_ip_addresses`.
DESCRIPTION
  value       = azurerm_windows_web_app.this.possible_outbound_ip_addresses
}

output "public_network_access_enabled" {
  description = <<DESCRIPTION
Should public network access be enabled for the Web App. Defaults to `true`.
DESCRIPTION
  value       = azurerm_windows_web_app.this.public_network_access_enabled
}

output "resource_group_name" {
  description = <<DESCRIPTION
The name of the Resource Group where the Windows Web App should exist. Changing this forces a new Windows Web App to be created.
DESCRIPTION
  value       = azurerm_windows_web_app.this.resource_group_name
}

output "service_plan_id" {
  description = <<DESCRIPTION
The ID of the Service Plan that this Windows App Service will be created in.
DESCRIPTION
  value       = azurerm_windows_web_app.this.service_plan_id
}

output "site_credential" {
  value     = azurerm_windows_web_app.this.site_credential
  sensitive = true
}

output "tags" {
  description = <<DESCRIPTION
A mapping of tags which should be assigned to the Windows Web App.
DESCRIPTION
  value       = azurerm_windows_web_app.this.tags
}

output "virtual_network_backup_restore_enabled" {
  description = <<DESCRIPTION
Whether backup and restore operations over the linked virtual network are enabled. Defaults to `false`.
DESCRIPTION
  value       = azurerm_windows_web_app.this.virtual_network_backup_restore_enabled
}

output "virtual_network_image_pull_enabled" {
  description = <<DESCRIPTION
Whether traffic for the image pull should be routed over the virtual network.
DESCRIPTION
  value       = azurerm_windows_web_app.this.virtual_network_image_pull_enabled
}

output "virtual_network_subnet_id" {
  description = <<DESCRIPTION
The subnet id which will be used by this Web App for [regional virtual network integration](https://docs.microsoft.com/en-us/azure/app-service/overview-vnet-integration#regional-virtual-network-integration).
DESCRIPTION
  value       = azurerm_windows_web_app.this.virtual_network_subnet_id
}

output "webdeploy_publish_basic_authentication_enabled" {
  description = <<DESCRIPTION
Should the default WebDeploy Basic Authentication publishing credentials enabled. Defaults to `true`.
DESCRIPTION
  value       = azurerm_windows_web_app.this.webdeploy_publish_basic_authentication_enabled
}

output "zip_deploy_file" {
  description = <<DESCRIPTION
The local path and filename of the Zip packaged application to deploy to this Windows Web App. **Note:** Using this value requires either `WEBSITE_RUN_FROM_PACKAGE=1` or `SCM_DO_BUILD_DURING_DEPLOYMENT=true` to be set on the App in `app_settings`.
DESCRIPTION
  value       = azurerm_windows_web_app.this.zip_deploy_file
}

output "auth_settings" {
  value     = azurerm_windows_web_app.this.auth_settings
  sensitive = true
}

output "auth_settings_v2" {
  value = azurerm_windows_web_app.this.auth_settings_v2
}

output "backup" {
  value     = azurerm_windows_web_app.this.backup
  sensitive = true
}

output "connection_string" {
  description = <<DESCRIPTION
One or more `connection_string` blocks as defined below.
DESCRIPTION
  value       = azurerm_windows_web_app.this.connection_string
  sensitive   = true
}

output "identity" {
  value = azurerm_windows_web_app.this.identity
}

output "logs" {
  value     = azurerm_windows_web_app.this.logs
  sensitive = true
}

output "site_config" {
  value     = azurerm_windows_web_app.this.site_config
  sensitive = true
}

output "sticky_settings" {
  value = azurerm_windows_web_app.this.sticky_settings
}

output "storage_account" {
  description = <<DESCRIPTION
One or more `storage_account` blocks as defined below.
DESCRIPTION
  value       = azurerm_windows_web_app.this.storage_account
  sensitive   = true
}

output "timeouts" {
  value = azurerm_windows_web_app.this.timeouts
}
