# Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
# This product includes software developed at Datadog (https://www.datadoghq.com/) Copyright 2026 Datadog, Inc.

# This file is generated by scripts/set-module-version.sh

locals {
  module_version = "1.1.0"
}
