# Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
# This product includes software developed at Datadog (https://www.datadoghq.com/) Copyright 2026 Datadog, Inc.

# DO NOT EDIT: This file is generated by terraform-autogen. Update the autogen_config.json file to change the generated code.

output "app_metadata" {
  description = <<DESCRIPTION
A `app_metadata`.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.app_metadata
}

output "app_service_id" {
  description = <<DESCRIPTION
The ID of the Linux Web App this Deployment Slot will be part of.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.app_service_id
}

output "app_settings" {
  description = <<DESCRIPTION
A map of key-value pairs of App Settings.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.app_settings
  sensitive   = true
}

output "client_affinity_enabled" {
  description = <<DESCRIPTION
Should Client Affinity be enabled?
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.client_affinity_enabled
}

output "client_certificate_enabled" {
  description = <<DESCRIPTION
Should Client Certificates be enabled?
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.client_certificate_enabled
}

output "client_certificate_exclusion_paths" {
  description = <<DESCRIPTION
Paths to exclude when using client certificates, separated by ;
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.client_certificate_exclusion_paths
}

output "client_certificate_mode" {
  description = <<DESCRIPTION
The Client Certificate mode. Possible values are `Required`, `Optional`, and `OptionalInteractiveUser`. This property has no effect when `client_cert_enabled` is `false`. Defaults to `Required`.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.client_certificate_mode
}

output "custom_domain_verification_id" {
  description = <<DESCRIPTION
The identifier used by App Service to perform domain ownership verification via DNS TXT record.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.custom_domain_verification_id
  sensitive   = true
}

output "default_hostname" {
  description = <<DESCRIPTION
The default hostname of the Linux Web App.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.default_hostname
}

output "enabled" {
  description = <<DESCRIPTION
Should the Linux Web App be enabled? Defaults to `true`.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.enabled
}

output "ftp_publish_basic_authentication_enabled" {
  description = <<DESCRIPTION
Should the default FTP Basic Authentication publishing profile be enabled. Defaults to `true`.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.ftp_publish_basic_authentication_enabled
}

output "hosting_environment_id" {
  description = <<DESCRIPTION
The ID of the App Service Environment used by App Service Slot.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.hosting_environment_id
}

output "https_only" {
  description = <<DESCRIPTION
Should the Linux Web App require HTTPS connections. Defaults to `false`.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.https_only
}

output "id" {
  description = <<DESCRIPTION
The ID of the Linux Web App.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.id
}

output "key_vault_reference_identity_id" {
  description = <<DESCRIPTION
The User Assigned Identity ID used for accessing KeyVault secrets. The identity must be assigned to the application in the `identity` block. [For more information see - Access vaults with a user-assigned identity](https://docs.microsoft.com/azure/app-service/app-service-key-vault-references#access-vaults-with-a-user-assigned-identity).
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.key_vault_reference_identity_id
}

output "kind" {
  description = <<DESCRIPTION
The Kind value for this Linux Web App.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.kind
}

output "name" {
  description = <<DESCRIPTION
The name which should be used for this Linux Web App Slot. Changing this forces a new Linux Web App Slot to be created.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.name
}

output "outbound_ip_address_list" {
  description = <<DESCRIPTION
A list of outbound IP addresses - such as `["52.23.25.3", "52.143.43.12"]`
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.outbound_ip_address_list
}

output "outbound_ip_addresses" {
  description = <<DESCRIPTION
A comma-separated list of outbound IP addresses - such as `52.23.25.3,52.143.43.12`.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.outbound_ip_addresses
}

output "possible_outbound_ip_address_list" {
  description = <<DESCRIPTION
A `possible_outbound_ip_address_list`.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.possible_outbound_ip_address_list
}

output "possible_outbound_ip_addresses" {
  description = <<DESCRIPTION
A comma-separated list of outbound IP addresses - such as `52.23.25.3,52.143.43.12,52.143.43.17` - not all of which are necessarily in use. Superset of `outbound_ip_addresses`.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.possible_outbound_ip_addresses
}

output "public_network_access_enabled" {
  description = <<DESCRIPTION
Should public network access be enabled for the Web App. Defaults to `true`.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.public_network_access_enabled
}

output "service_plan_id" {
  description = <<DESCRIPTION
The ID of the Service Plan in which to run this slot. If not specified the same Service Plan as the Linux Web App will be used.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.service_plan_id
}

output "site_credential" {
  value     = azurerm_linux_web_app_slot.this.site_credential
  sensitive = true
}

output "tags" {
  description = <<DESCRIPTION
A mapping of tags that should be assigned to the Linux Web App.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.tags
}

output "virtual_network_backup_restore_enabled" {
  description = <<DESCRIPTION
Whether backup and restore operations over the linked virtual network are enabled. Defaults to `false`.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.virtual_network_backup_restore_enabled
}

output "virtual_network_subnet_id" {
  description = <<DESCRIPTION
The subnet id which will be used by this Web App Slot for [regional virtual network integration](https://docs.microsoft.com/en-us/azure/app-service/overview-vnet-integration#regional-virtual-network-integration).
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.virtual_network_subnet_id
}

output "vnet_image_pull_enabled" {
  description = <<DESCRIPTION
Should the traffic for the image pull be routed over virtual network enabled. Defaults to `false`.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.vnet_image_pull_enabled
}

output "webdeploy_publish_basic_authentication_enabled" {
  description = <<DESCRIPTION
Should the default WebDeploy Basic Authentication publishing credentials enabled. Defaults to `true`.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.webdeploy_publish_basic_authentication_enabled
}

output "zip_deploy_file" {
  description = <<DESCRIPTION
The local path and filename of the Zip packaged application to deploy to this Windows Web App. **Note:** Using this value requires `WEBSITE_RUN_FROM_PACKAGE=1` on the App in `app_settings`.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.zip_deploy_file
}

output "auth_settings" {
  value     = azurerm_linux_web_app_slot.this.auth_settings
  sensitive = true
}

output "auth_settings_v2" {
  value = azurerm_linux_web_app_slot.this.auth_settings_v2
}

output "backup" {
  value     = azurerm_linux_web_app_slot.this.backup
  sensitive = true
}

output "connection_string" {
  description = <<DESCRIPTION
One or more `connection_string` blocks as defined below.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.connection_string
  sensitive   = true
}

output "identity" {
  description = <<DESCRIPTION
An `identity` block as defined below, which contains the Managed Service Identity information for this App Service.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.identity
}

output "logs" {
  value     = azurerm_linux_web_app_slot.this.logs
  sensitive = true
}

output "site_config" {
  value     = azurerm_linux_web_app_slot.this.site_config
  sensitive = true
}

output "storage_account" {
  description = <<DESCRIPTION
One or more `storage_account` blocks as defined below.
DESCRIPTION
  value       = azurerm_linux_web_app_slot.this.storage_account
  sensitive   = true
}

output "timeouts" {
  value = azurerm_linux_web_app_slot.this.timeouts
}
