#!/usr/bin/env bash
# Sets module_version across all submodules by overwriting module_version.tf.
# Usage: ./scripts/set-module-version.sh 1.0.3

set -euo pipefail

if [ $# -ne 1 ]; then
  echo "Usage: $0 <version>" >&2
  exit 1
fi

VERSION="$1"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

for dir in "$REPO_ROOT"/modules/*/; do
  cat > "$dir/module_version.tf" <<EOF
# Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
# This product includes software developed at Datadog (https://www.datadoghq.com/) Copyright 2026 Datadog, Inc.

# This file is generated by scripts/set-module-version.sh

locals {
  module_version = "${VERSION}"
}
EOF
  echo "Updated $(basename "$dir")/module_version.tf"
done
