name: Terraform Lint Check

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '**'

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@1cf010d3c7aef302051ccdb68c14c5dc2efa34ef # v6

      - name: Show TFLint version
        run: tflint --version

      - name: Run TFLint
        run: |
          tflint --recursive --config "$(pwd)/.tflint.hcl"
          echo All files passed the linter!
